@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.token}}
@refreshToken = {{refresh_token.response.body.token}}

# @name create_account
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Matteus Varlesse",
  "email": "varlesse04@gmail.com",
  "password": "123456",
  "role": "student"
}
###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "varlesse04@gmail.com",
  "password": "123456"
}
###

# @name refresh_token
PATCH {{baseUrl}}/token/refresh
###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta",
  "content": "Teste"
}
###
